import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseDiagram } from "../../src/pugflow/web/parser.mjs";
import { layoutDiagram } from "../../src/pugflow/web/layout.mjs";
import { pugDefinitionsToStyleSheet } from "../../src/pugflow/web/style-sheet.mjs";

test("the built-in showcase presents two simple independent branch-and-merge graphs", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const document = app.match(/const EXAMPLE_DOCUMENT = `([\s\S]*?)`;/)?.[1];
  assert.ok(document, "could not locate the built-in example");
  const start = document.indexOf("#canvas");
  const result = parseDiagram(document.slice(start), pugDefinitionsToStyleSheet(document.slice(0, start)));
  assert.deepEqual(result.errors, []);
  assert.equal(result.nodes.length, 10);
  assert.deepEqual(result.groups.map((group) => group.id), ["checkout", "publishing"]);
  assert.deepEqual(result.groups.map((group) => group.layer), [1, 0]);
  assert.deepEqual(result.groups.map((group) => group.fill), ["#2563eb80", "#7c3aed80"]);
  assert.equal(result.edges.filter((edge) => edge.to === "receipt").length, 2);
  assert.equal(result.edges.filter((edge) => edge.to === "publish").length, 2);
  assert.ok(result.edges.filter((edge) => ["receipt", "publish"].includes(edge.to)).every((edge) => edge.kind === "merge"));
  const ownership = new Map(result.groups.flatMap((group) => group.nodeIds.map((id) => [id, group.id])));
  assert.ok(result.edges.every((edge) => ownership.get(edge.from) === ownership.get(edge.to)));
  assert.ok(result.edges.filter((edge) => ownership.get(edge.from) === "checkout").every((edge) => edge.layoutDirection === "down"));
  assert.ok(result.edges.filter((edge) => ownership.get(edge.from) === "publishing").every((edge) => edge.layoutDirection === "right"));
  for (const [from, to] of [["cart", "payment"], ["payment", "retry"]]) {
    const edge = result.edges.find((candidate) => candidate.from === from && candidate.to === to);
    assert.equal(edge?.sourceFace, "bottom");
    assert.equal(edge?.targetFace, "top");
  }
  const approval = result.edges.find((edge) => edge.from === "payment" && edge.to === "approve");
  assert.equal(approval?.sourceFace, "bottom");
  assert.equal(approval?.targetFace, "left");
  const receiptEdges = result.edges.filter((edge) => edge.to === "receipt");
  assert.deepEqual(receiptEdges.map((edge) => edge.from), ["retry", "approve"]);
  assert.ok(receiptEdges.every((edge) => edge.sourceFace === "bottom" && edge.targetFace === "top"));
  const checkoutNodeIds = new Set(result.groups.find((group) => group.id === "checkout").nodeIds);
  const checkoutLayout = layoutDiagram(
    result.nodes.filter((node) => checkoutNodeIds.has(node.id)),
    result.edges.filter((edge) => checkoutNodeIds.has(edge.from) && checkoutNodeIds.has(edge.to)),
  );
  const placed = new Map(checkoutLayout.nodes.map((node) => [node.id, node]));
  const centerX = (node) => node.x + node.width / 2;
  assert.equal(centerX(placed.get("receipt")), (centerX(placed.get("retry")) + centerX(placed.get("approve"))) / 2);
  const parsed = new Map(result.nodes.map((node) => [node.id, node]));
  assert.equal(parsed.get("cart")?.annotations.length, 1);
  assert.equal(parsed.get("receipt")?.annotations.length, 1);
  assert.equal(parsed.get("draft")?.annotations.length, 1);
  assert.equal(parsed.get("publish")?.annotations.length, 1);
  assert.ok(result.nodes.every((node) => !node.style.image));
  assert.equal(parsed.get("cart")?.style.color, "#ffffff");
  assert.equal(parsed.get("draft")?.style.shape, "hexagon");
});

test("source saving writes the active document through a system file handle", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  assert.doesNotMatch(app, /showDirectoryPicker/);
  assert.match(app, /showSaveFilePicker/);
  assert.match(app, /handle\.createWritable\(\)/);
  assert.doesNotMatch(app, /anchor\.download = sourceFilename/);
  assert.match(html, /id="save-source" type="button">Save<\/button>/);
  assert.match(html, /id="save-source-as" type="button">Save As…<\/button>/);
});

test("editor exposes flat layered graphs and scoped connection controls", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../../src/pugflow/web/styles.css", import.meta.url), "utf8");
  const renderer = readFileSync(new URL("../../src/pugflow/web/pugflow.mjs", import.meta.url), "utf8");
  assert.match(html, /id="new-pug"/);
  assert.match(html, /id="new-css"/);
  assert.match(html, /id="toggle-source"/);
  assert.doesNotMatch(app, /data-graph-parent|data-break-out-graph|reparentGraph|Create nested graph/);
  assert.match(app, /Graph Layer<select data-graph-field="layer-order"/);
  assert.match(app, /graphSelections\.length > 1[\s\S]*Align \/ distribute[\s\S]*return;/);
  assert.match(renderer, /event\.shiftKey \|\| event\.ctrlKey \|\| event\.metaKey/);
  assert.match(html, /id="color-picker-popup"[^>]*hidden/);
  assert.match(html, /id="color-picker-saturation"[^>]*canvas|<canvas id="color-picker-saturation"/);
  assert.match(html, /id="color-picker-hue" type="range"/);
  assert.match(html, /id="color-picker-alpha" type="range"/);
  assert.match(html, /id="color-picker-h" type="number"/);
  assert.match(html, /id="color-picker-s" type="number"/);
  assert.match(html, /id="color-picker-v" type="number"/);
  assert.match(html, /id="color-picker-marker"/);
  assert.doesNotMatch(html, /id="color-picker-popup-none"/);
  assert.doesNotMatch(html, /color-picker-popup-input[^>]*type="color"/);
  assert.match(app, /popupAlpha/);
  assert.match(app, /Math\.round\(popupAlpha \* 255\)/);
  assert.match(app, /transparent\|none[\s\S]*renderColorDecorators|renderColorDecorators[\s\S]*transparent\|none/);
  assert.match(app, /openColorPickerPopup\([^,]+, color, replaceColor\)/);
  assert.match(app, /"sbd-color"/);
  assert.match(app, /match\[6\] \? "sbd-color"/);
  assert.match(styles, /::highlight\(sbd-color\)/);
  assert.match(styles, /::highlight\(sbd-number\)/);
  assert.doesNotMatch(html, /builder-diagram-no-(?:fill|outline)/);
  assert.match(app, />Send to front<\/option><option value="back">Send to back/);
  assert.doesNotMatch(app, /New front layer/);
  assert.match(app, /data-connected-field="source-face"/);
  assert.match(app, /data-connected-field="target-face"/);
  assert.match(app, /<summary>Flows <small>/);
  assert.doesNotMatch(app, /data-connected-field="arrow-style"/);
  assert.doesNotMatch(app, /data-connected-field="width"/);
  assert.doesNotMatch(app, /data-connected-field="roundness"/);
  assert.match(app, /data-line-field="arrow-style"/);
  assert.match(app, /data-line-field="stroke-style"/);
  assert.match(app, /data-line-field="roundness"/);
  assert.match(html, /class="inspector-footer"[^>]*>.*id="save-reusable-style"/);
  assert.match(html, /id="style-builder-preview"[^>]*readonly/);
  assert.match(html, /<button class="primary" value="default">Save<\/button>/);
  assert.doesNotMatch(app, />Save as reusable (?:node|line|annotation) type/);
  assert.match(app, /<label>ID <small>optional<\/small><input data-node-field="id"/);
  assert.match(app, /data-add-annotation>\+ Add Annotation/);
  assert.match(html, /id="annotation-builder-position"/);
  assert.match(html, /id="annotation-builder-text"/);
  assert.match(app, /data-delete-annotation/);
  assert.match(app, /data-remove-annotation-offset/);
  assert.match(app, /data-group-as-graph/);
  assert.match(html, /id="builder-from-graph"/);
  assert.match(html, /id="builder-to-graph"/);
  assert.match(html, /id="builder-sources"[^>]*role="listbox"/);
  assert.match(html, /id="builder-targets"[^>]*role="listbox"/);
  assert.match(html, /id="builder-from-direction"/);
  assert.match(html, /id="builder-to-direction"/);
  assert.match(html, /id="toggle-layers"/);
  assert.match(html, /id="layers-list"[^>]*role="list"/);
  assert.match(html, /<main class="layers-collapsed">/);
  assert.match(html, /class="toggle-label">Source/);
  assert.match(html, /class="toggle-label">Layers/);
  assert.match(app, /draggable="true" data-layer-graph/);
  assert.match(app, /setStructuralField\(nextSource, group\.lineNumber, "layer"/);
  assert.match(app, /const targetGraph = sourceGraph/);
  assert.doesNotMatch(app, /removeNodeFields\(nextSource, node\.lineNumber, \["offset", "label-offset"\]\)/);
  assert.match(app, /change\.kind === "route"/);
  assert.match(renderer, /Math\.max\(sourceLayer, targetLayer\)/);
  assert.match(renderer, /class: "diagram-layer"/);
  assert.ok(renderer.indexOf('class: "connector-layer"') < renderer.indexOf('class: "graph-node-layer"'));
  assert.doesNotMatch(html, /id="add-merge"/);
  assert.match(styles, /\.inspector-drag-handle \{ position: sticky/);
  assert.match(styles, /\.canvas-inspector \{ position: fixed/);
  assert.match(app, /canvasShell\.getBoundingClientRect\(\)/);
  assert.match(app, /new ResizeObserver\(constrainInspectorToCanvas\)\.observe\(canvasShell\)/);
  assert.match(styles, /writing-mode: vertical-rl/);
  assert.match(styles, /\.inspector-footer \{ position: sticky/);
  assert.match(styles, /button\.danger[^}]*var\(--danger\)[^}]*background:/);
  assert.match(styles, /\.subdiagram-selection-outline \{ opacity: 0/);
  assert.match(styles, /svg\.interactive \.subdiagram-hit:hover ~ \.subdiagram-selection-outline/);
  assert.match(styles, /opacity: var\(--graph-proximity/);
  assert.ok(renderer.indexOf('class: "subdiagram-frame"') < renderer.indexOf('class: "subdiagram-selection-outline"'));
  assert.match(styles, /selected-element > \.subdiagram-selection-outline \{ opacity: 1/);
  assert.doesNotMatch(styles, /:focus > \.subdiagram-selection-outline/);
  assert.doesNotMatch(app, /<summary>Typography<\/summary>/);
});

test("application startup does not wait for the math renderer", () => {
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  const appImport = html.indexOf('import("./app.mjs")');
  const mathAwait = html.indexOf("await window.MathJax.startup.promise");
  assert.ok(appImport >= 0 && mathAwait >= 0 && appImport < mathAwait);
  assert.match(html, /pugflow-math-ready/);
});
