import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseDiagram } from "../../src/pugflow/web/parser.mjs";
import { compileStyleSheet, pugDefinitionsToStyleSheet } from "../../src/pugflow/web/style-sheet.mjs";
import { ADDITIONAL_DEMOS } from "../../src/pugflow/web/demo-sources.mjs";

test("documentation starts as a standalone HTML document", () => {
  const docs = readFileSync(new URL("../../src/pugflow/web/docs.html", import.meta.url), "utf8");
  assert.match(docs, /^<!doctype html>/i);
});

test("source editor preserves standard selection, deletion, and copy shortcuts", () => {
  const editor = readFileSync(new URL("../../src/pugflow/web/text-editor.mjs", import.meta.url), "utf8");
  const vim = readFileSync(new URL("../../src/pugflow/web/vim-mode.mjs", import.meta.url), "utf8");
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  assert.match(editor, /event\.key\.toLowerCase\(\) === "a"[\s\S]*setSelectionRange\(0, element\.value\.length\)/);
  assert.match(editor, /\["Backspace", "Delete"\][\s\S]*setRangeText\("", element\.selectionStart, element\.selectionEnd, "end"\)/);
  assert.match(vim, /key\.toLowerCase\(\) === "c" && textarea\.selectionStart === textarea\.selectionEnd/);
  assert.match(app, /source\.addEventListener\("beforeinput"[\s\S]*canvasUndo\.push\(pugSource\)/);
  assert.match(app, /activeDocument === "pug"[\s\S]*\["z", "y"\][\s\S]*undoCanvas\(\)/);
});

test("source completions behave like an IDE near the caret", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../../src/pugflow/web/styles.css", import.meta.url), "utf8");
  assert.match(app, /graph: new Set\(\["node", "image", "flow"/);
  assert.match(app, /scope === item\.reusableKind/);
  assert.match(app, /replace\(\/\^\\\.\/, ""\)\.includes\(prefix\)/);
  assert.match(app, /leftRank - rightRank \|\| leftLabel\.localeCompare\(rightLabel\)/);
  assert.match(app, /item\.insert\.replaceAll\("\\n", `\\n\$\{indentation\}`\)/);
  assert.match(app, /if \(\/\^\[a-z@\.\#-\]\$\/i\.test\(event\.data \?\? ""\)\) showCompletions\(\)/);
  assert.doesNotMatch(app, /event\.inputType === "insertLineBreak"[^;]*showCompletions/);
  assert.match(app, /event\.key === "ArrowDown" \|\| event\.key === "ArrowUp"[\s\S]*activeCompletion = \(activeCompletion \+ direction/);
  assert.match(app, /if \(!completionMenu\.hidden\)[\s\S]*event\.key === "Tab"[\s\S]*acceptCompletion\(\)/);
  assert.doesNotMatch(app, /event\.key !== "Tab"[\s\S]*showCompletions\(\)/);
  assert.match(app, /if \(event\.key === "Enter"\) hideCompletions\(\)/);
  assert.match(app, /function positionCompletionMenu\(\)[\s\S]*caretRect[\s\S]*completionMenu\.style\.translate/);
  assert.match(styles, /\.completion-menu \{[\s\S]*top: 0;[\s\S]*left: 0;/);
});

test("the built-in showcase presents a restrained layered production architecture", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const definitions = app.match(/const EXAMPLE_DEFINITIONS = `([\s\S]*?)`;/)?.[1];
  const indentedCanvas = app.match(/const EXAMPLE_CANVAS = `([\s\S]*?)`;/)?.[1];
  assert.ok(definitions && indentedCanvas, "could not locate the built-in example");
  const canvas = indentedCanvas.trim().split("\n").map((line) => line.startsWith("  ") ? line.slice(2) : line).join("\n");
  assert.doesNotMatch(canvas, /#canvas|#diagram/);
  const result = parseDiagram(canvas, pugDefinitionsToStyleSheet(definitions));
  assert.deepEqual(result.errors, []);
  assert.equal(result.nodes.length, 14);
  assert.deepEqual(result.groups.map((group) => group.id), ["edge", "application", "operations"]);
  assert.deepEqual(result.groups.map((group) => group.layer), [2, 1, 0]);
  assert.ok(result.groups.every((group) => group.placement === "below" && group.relativeTo === null));
  assert.deepEqual(result.groups.map((group) => group.fill), ["#3b82f6e8", "#fef3c750", "#050505f5"]);
  assert.ok(result.groups.every((group) => group.labelPosition === "inside" && group.align === "center"));
  assert.deepEqual([result.groups[0].fontFamily, result.groups[2].fontFamily], ["SFMono-Regular, Menlo, Consolas, monospace", "Avenir Next Condensed, Arial Narrow, sans-serif"]);
  assert.deepEqual([result.groups[2].outline, result.groups[2].outlineWidth], ["#ff2bd6", 2]);
  const ownership = new Map(result.groups.flatMap((group) => group.nodeIds.map((id) => [id, group.id])));
  assert.equal(result.edges.filter((edge) => ownership.get(edge.from) !== ownership.get(edge.to)).length, 2);
  const policyToApi = result.edges.find((edge) => edge.from === "policy" && edge.to === "api");
  assert.equal(policyToApi?.graphId, null);
  assert.deepEqual([policyToApi?.layoutDirection, policyToApi?.sourceFace, policyToApi?.targetFace], ["down", "bottom", "top"]);
  assert.ok(result.edges.filter((edge) => edge.graphId === null).every((edge) => edge.color === "#000000" && edge.outline === "#ffffff" && edge.outlineWidth === 1.5));
  assert.ok(result.edges.filter((edge) => edge.graphId === null).every((edge) => edge.annotationAboveStyle.color === "#000000" && edge.annotationAboveStyle.textOutline === "#ffffff" && edge.annotationAboveStyle.textOutlineWidth === 3));
  assert.equal(result.edges.some((edge) => edge.from === "gateway" && edge.to === "collector"), false);
  assert.ok(result.edges.filter((edge) => edge.graphId === "operations" && edge.to !== "oncall").every((edge) => edge.style === "dotted" && edge.color === "#00f5ff"));
  for (const [from, to] of [["client", "gateway"], ["api", "orders"]]) {
    const edge = result.edges.find((candidate) => candidate.from === from && candidate.to === to);
    assert.equal(edge?.direction, "forward");
  }
  const parsed = new Map(result.nodes.map((node) => [node.id, node]));
  assert.equal(parsed.get("client")?.annotations.length, 1);
  assert.equal(parsed.get("event-stream")?.annotations.length, 0);
  assert.deepEqual([parsed.get("gateway")?.layer, parsed.get("identity")?.layer, parsed.get("policy")?.layer], [2, 1, 0]);
  assert.ok(result.nodes.some((node) => node.kind === "image" && node.style.source.startsWith("https://")));
  assert.deepEqual([parsed.get("gateway")?.style.fill, parsed.get("gateway")?.style.color, parsed.get("gateway")?.style.outline, parsed.get("gateway")?.style.fontFamily], ["#2563eb", "#ffffff", "#ffffff", "SFMono-Regular, Menlo, Consolas, monospace"]);
  assert.equal(parsed.get("policy")?.style.shape, "diamond");
  assert.deepEqual([parsed.get("api")?.style.shape, parsed.get("api")?.style.fill, parsed.get("api")?.style.color, parsed.get("api")?.style.outline], ["square", "#172554", "#fef3c7", "#fde68a"]);
  assert.deepEqual([parsed.get("api")?.style.shadowOffsetX, parsed.get("api")?.style.shadowOffsetY, parsed.get("api")?.style.shadowBlur], [5, 5, 0]);
  assert.deepEqual([parsed.get("primary-db")?.style.fill, parsed.get("primary-db")?.style.color, parsed.get("primary-db")?.style.outline, parsed.get("primary-db")?.style.outlineStyle], ["#fef3c7", "#172554", "#172554", "dotted"]);
  assert.ok(result.edges.filter((edge) => edge.graphId === "application").every((edge) => edge.roundness === 0 && edge.color === "#172554"));
  assert.deepEqual([parsed.get("collector")?.style.shape, parsed.get("metrics")?.style.shape, parsed.get("oncall")?.style.shape], ["hexagon", "pill", "diamond"]);
  assert.deepEqual([parsed.get("collector")?.style.fill, parsed.get("collector")?.style.color, parsed.get("collector")?.style.outline, parsed.get("metrics")?.style.color, parsed.get("metrics")?.style.outlineStyle], ["#050505", "#00f5ff", "#ff2bd6", "#fff200", "dotted"]);
  const incident = result.edges.find((edge) => edge.from === "alerting" && edge.to === "oncall");
  assert.equal(incident?.color, "#ff2bd6");
  assert.equal(incident?.annotationAboveStyle.color, "#ff2bd6");
  assert.equal(incident?.annotationAboveStyle.textOutline, "transparent");
  assert.equal(incident?.annotationAboveStyle.textOutlineWidth, 0);
});

test("the nine additional demos are distinct, styled, and valid", () => {
  assert.equal(ADDITIONAL_DEMOS.length, 9);
  assert.equal(new Set(ADDITIONAL_DEMOS.map((demo) => demo.name)).size, 9);
  for (const [index, demo] of ADDITIONAL_DEMOS.entries()) {
    const styles = compileStyleSheet(demo.css);
    assert.deepEqual(styles.errors, [], `demo ${index + 2} has invalid CSS`);
    const result = parseDiagram(demo.pug, demo.css);
    assert.deepEqual(result.errors, [], `demo ${index + 2} has invalid Pug`);
    assert.ok(result.nodes.length >= 4, `demo ${index + 2} should have at least four nodes`);
    assert.ok(result.edges.length >= 3, `demo ${index + 2} should have at least three flows`);
    assert.match(demo.pug, new RegExp(`Demo ${index + 2}`));
    assert.doesNotMatch(demo.pug, /#canvas|#diagram/);
  }
});

test("the demo collection balances linear and branching layouts", () => {
  const diagrams = ADDITIONAL_DEMOS.map((demo) => parseDiagram(demo.pug, demo.css));
  const diagramSizes = diagrams.map((diagram) => `${diagram.nodes.length}:${diagram.edges.length}`);
  const horizontalChains = diagrams.filter((diagram) =>
    diagram.nodes.length === 4
    && diagram.edges.length === 3
    && diagram.edges.every((edge) => edge.layoutDirection === "right"));
  const branching = diagrams.filter((diagram) => {
    const outgoing = new Map();
    for (const edge of diagram.edges) outgoing.set(edge.from, (outgoing.get(edge.from) ?? 0) + 1);
    return [...outgoing.values()].some((count) => count > 1);
  });
  assert.equal(new Set(diagramSizes).size, diagrams.length);
  assert.ok(diagrams.filter((diagram) => diagram.nodes.length >= 15).length >= 3);
  assert.equal(horizontalChains.length, 2);
  assert.ok(branching.length >= 6);
});

test("launch parameters select demos 1 through 10", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  assert.match(app, /requestedDemo >= 1 && requestedDemo <= DEMOS\.length/);
  assert.match(app, /DEMOS\[requestedDemo - 1\]/);
  assert.match(app, /`demo\$\{requestedDemo\}\.pug`/);
  assert.match(app, /`demo\$\{requestedDemo\}\.css`/);
});

test("source saving writes the active document through a system file handle", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  assert.doesNotMatch(app, /showDirectoryPicker/);
  assert.match(app, /showSaveFilePicker/);
  assert.match(app, /handle\.createWritable\(\)/);
  assert.doesNotMatch(app, /anchor\.download = sourceFilename/);
  assert.match(html, /id="save-source" type="button">Save<\/button>/);
  assert.match(html, /id="save-source-as" type="button">Save As…<\/button>/);
});

test("editor exposes flat layered graphs and scoped connection controls", () => {
  const app = readFileSync(new URL("../../src/pugflow/web/app.mjs", import.meta.url), "utf8");
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../../src/pugflow/web/styles.css", import.meta.url), "utf8");
  const diagramStyles = readFileSync(new URL("../../src/pugflow/web/pugflow.css", import.meta.url), "utf8");
  const renderer = readFileSync(new URL("../../src/pugflow/web/pugflow.mjs", import.meta.url), "utf8");
  assert.match(html, /id="new-pug"/);
  assert.match(html, /id="new-css"/);
  assert.match(html, /data-source-tab="pug"[^>]*>PUG<\/button>/);
  assert.match(app, /pugTab\.textContent = pugFileName \|\| "PUG"/);
  assert.match(app, /cssTab\.textContent = cssFileName \|\| "CSS"/);
  assert.doesNotMatch(app, /FileName === "Untitled\.(?:pug|css)"/);
  assert.match(app, /pugFileName = "";\s*pugFileHandle = null;[\s\S]*?activateDocument\("pug", true\)/);
  assert.match(app, /cssFileName = "";\s*cssFileHandle = null;[\s\S]*?activateDocument\("css", true\)/);
  assert.match(html, /<kbd>Ctrl<\/kbd>\+<kbd>Space<\/kbd> suggestions/);
  assert.match(html, /id="toggle-source"/);
  assert.match(html, /class="theme-toggle" id="theme" type="button"/);
  assert.match(html, /class="theme-sun"[^>]*><svg/);
  assert.match(html, /class="theme-moon"[^>]*><svg/);
  assert.doesNotMatch(html, /[☀☾✋]/);
  assert.doesNotMatch(html, /<select id="theme"/);
  assert.match(html, /<nav class="global-actions"[^>]*>/);
  assert.match(html, /id="add-diagram"/);
  assert.match(html, /id="open-save-export"/);
  assert.match(html, /id="open-copy-export"/);
  assert.match(html, /class="export-dialog" id="copy-export-dialog"[\s\S]*class="export-form"[\s\S]*id="copy-export-target"[\s\S]*id="copy-export-format"[\s\S]*id="copy-export-dpi"/);
  assert.match(html, /class="export-dialog" id="save-export-dialog"[\s\S]*class="export-form"[\s\S]*id="save-export-target"[\s\S]*id="save-export-format"[\s\S]*id="save-export-dpi"/);
  assert.match(styles, /\.export-form, #style-builder-form \{ padding: 16px; \}/);
  assert.match(styles, /\.export-dialog \{ width: min\(390px/);
  assert.match(app, /new Option\("Entire canvas", ""\)/);
  assert.match(app, /diagram\.toSVGString\(graphId\)/);
  assert.match(app, /diagram\.toPNGBlob\(Number\(copyExport\.dpi\.value\) \/ 96, graphId\)/);
  assert.doesNotMatch(html, /Live preview/);
  assert.match(html, /class="zoom-controls canvas-zoom-controls"/);
  assert.match(html, /class="zoom-controls canvas-mode-controls"[\s\S]*id="mode-select"[\s\S]*<svg[\s\S]*id="mode-pan"[\s\S]*<svg/);
  assert.doesNotMatch(html, /&#(?:9654|9995);/);
  assert.match(app, /modeSelectButton\.setAttribute\("aria-pressed", String\(mode === "select"\)\)/);
  assert.match(styles, /\.canvas-shell\.pan-mode \{ cursor: grab; touch-action: none; \}/);
  assert.match(styles, /\.canvas-shell\.pan-mode #diagram \{ pointer-events: none; user-select: none; \}/);
  assert.match(styles, /#diagram \{ width: max-content; min-width: 100%; height: max-content; min-height: 100%;/);
  assert.match(html, /<div class="canvas-shell"[^>]*>[\s\S]*?<\/div>\s*<div class="zoom-controls canvas-zoom-controls"/);
  assert.match(styles, /\.preview \{ position: relative;/);
  assert.match(styles, /\.canvas-zoom-controls \{ position: absolute;[^}]*right: 38px; bottom: 38px;/);
  assert.match(styles, /main\.layers-collapsed \.layers-toggle \{ position: fixed; z-index: 30;[^}]*right: 8px;/);
  assert.doesNotMatch(styles, /main\.layers-collapsed \.preview \{ padding-right:/);
  assert.doesNotMatch(app, /data-graph-parent|data-break-out-graph|reparentGraph|Create nested graph/);
  assert.match(app, /Layer \(\$\{group\.layer \?\? 0\}\)<select data-graph-field="layer-order"/);
  assert.match(app, /Position<select data-graph-field="label-position"/);
  assert.match(app, /Horizontal placement<select data-graph-field="align"/);
  assert.match(app, /Vertical placement<select data-graph-field="vertical-align"/);
  assert.match(app, /Offset<input value="\(\$\{group\.labelOffsetX \?\? 0\}, \$\{group\.labelOffsetY \?\? 0\}\)" readonly/);
  assert.match(app, /change\.kind === "graph-label"[\s\S]*"label-offset"/);
  assert.match(app, /fontOptions\("graph", group\)/);
  assert.match(app, /fontOptions\("graph", group\)/);
  assert.match(app, /data-graph-field="x-spacing".*data-graph-field="y-spacing"/);
  assert.match(app, /class="preview-stage graph-preview-stage"\$\{previewStageBackground\(group, false\)\}/);
  assert.match(app, /data-sidecar="graph-frame"/);
  assert.match(app, /data-sidecar="graph-title"[^>]*[\s\S]*?>label<\/button>/);
  assert.doesNotMatch(app, /data-sidecar="graph-layout"/);
  assert.doesNotMatch(app, /graph-preview-node|graph-preview-nodes|>Layout<\/strong>/);
  assert.doesNotMatch(app, /graph-annotations|annotationChip\("graph/);
  assert.doesNotMatch(styles, /\.graph-preview-node(?:s|\.more)?\s*\{/);
  assert.match(app, /<summary>Layout and spacing<\/summary>[\s\S]*data-graph-field="x-spacing"[\s\S]*data-graph-field="y-spacing"[\s\S]*data-graph-field="placement"[\s\S]*data-graph-field="relative-to"[\s\S]*data-graph-field="layer-order"[\s\S]*Offset/);
  assert.match(styles, /\.canvas-inspector \.graph-preview-title \{[^}]*border-color: transparent;[^}]*background: transparent;[^}]*box-shadow: none;/);
  assert.match(styles, /\.canvas-inspector \.graph-preview-title:hover, \.canvas-inspector \.graph-preview-title:focus-visible \{[^}]*border-color:[^}]*background:/);
  assert.match(styles, /\.canvas-inspector \.graph-preview-title\.active-part \{[^}]*border-color:[^}]*background:/);
  assert.match(app, /const horizontalAlign = align === "right" \? "flex-end" : align === "center" \? "center" : "flex-start"/);
  assert.match(app, /const verticalPlacement = verticalAlign === "bottom" \? "flex-end" : verticalAlign === "middle" \? "center" : "flex-start"/);
  assert.match(app, /data-label-position="\$\{group\?\.labelPosition \?\? "inside"\}"[^>]*justify-content:\$\{horizontalAlign\};align-items:\$\{verticalPlacement\}/);
  assert.match(styles, /\.graph-preview \{[^}]*width: min\(100%, 190px\);/);
  assert.match(styles, /\.graph-preview-frame > \.graph-preview-title \{[^}]*top: 50%; left: 50%;[^}]*width: calc\(100% - 24px\); height: calc\(100% - 14px\);[^}]*translate: -50% -50%;/);
  assert.match(styles, /\.graph-preview > \.graph-preview-title \{ min-height: 24px; \}/);
  assert.match(styles, /\.canvas-inspector \.inspector-inline-field button, \.inspector-sidecar \.inspector-inline-field button \{[^}]*height: 29px;[^}]*margin: 0;/);
  assert.match(styles, /\.canvas-inspector \.inspector-inline-field > label, \.inspector-sidecar \.inspector-inline-field > label \{[^}]*margin: 0;/);
  assert.match(app, /data-graph-field="placement"/);
  assert.match(app, /data-graph-field="relative-to"/);
  assert.match(html, /id="builder-diagram-placement"/);
  assert.match(html, /id="builder-diagram-relative-to"/);
  assert.doesNotMatch(html, /id="builder-ports"/);
  assert.match(app, /data-node-field="\$\{face\}-ports"/);
  assert.doesNotMatch(app, /class="preview-part preview-face/);
  assert.doesNotMatch(styles, /\.preview-face\s*\{/);
  assert.match(app, /<details class="face-connections" open><summary>Face connections<\/summary><div class="inspector-grid">\$\{faceControls\}<\/div><\/details>/);
  assert.match(app, />label<\/span>/);
  assert.match(app, /annotation-position="\$\{position\}"[^>]*>\$\{label\}/);
  assert.match(app, /Horizontal alignment<select data-node-field="align"/);
  assert.match(app, /Vertical alignment<select data-node-field="vertical-align"/);
  assert.match(styles, /\.node-preview-stage \{ gap: 2px; padding-inline: 34px; \}/);
  assert.match(styles, /\.node-preview \{ display: grid; width: 100%; place-items: center; padding: 4px 0; \}/);
  assert.match(styles, /\.node-preview-box \{[^}]*width: 138px; height: 58px;/);
  assert.match(styles, /\.node-preview-stage > \.preview-face-add\[data-face-add="top"\] \{ top: -7px;/);
  assert.match(styles, /\.node-preview-stage > \.preview-face-add\[data-face-add="left"\], \.node-preview-stage > \.preview-face-add\[data-face-add="right"\] \{ width: 14px; height: 22px;/);
  assert.match(app, /class="image-preview-box preview-part" data-sidecar="image-box"/);
  assert.match(app, /function imageBoxSidecar\(image\)/);
  assert.match(app, /opacity:\$\{image\.style\.opacity\};\$\{escapeHtml\(previewShadowCss\(image\.style\)\)\}/);
  assert.match(renderer, /shape\.removeAttribute\("filter"\)/);
  assert.match(renderer, /const imageShadow = svgElement\("g", \{ filter: ensureShadow\(defs, node\) \}\)/);
  assert.match(renderer, /imageShadow\.append\(svgElement\("image"/);
  assert.match(app, /imagePreviewMarkup\(image\)[\s\S]*nodeConnectionsSection\(image\)/);
  assert.match(renderer, /kind: "node-resize"/);
  assert.match(renderer, /kind: "graph-resize"/);
  assert.match(renderer, /packGraphs\(visualNodes, graph\.groups \?\? \[\], colors, 80, layout\.nodes\)/);
  assert.match(styles, /\.entry\.selected-element > \.resize-handles/);
  assert.doesNotMatch(app, /preview-face-add-outer/);
  assert.doesNotMatch(styles, /\.node-preview-label \{[^}]*text-shadow:/);
  assert.match(styles, /\.node-preview-label \{[^}]*top: 50%; left: 50%;[^}]*width: calc\(100% - 24px\); height: calc\(100% - 14px\);[^}]*translate: -50% -50%;[^}]*background: transparent;/);
  assert.match(app, /previewFontStyle\(node\.style\).*justify-content:/);
  assert.match(app, /entries\[0\].*previewFontStyle\(entries\[0\]\)/);
  assert.match(app, /font-size:\$\{Math\.max\(Number\(style\.fontSize\) \|\| 12, 1\)\}px/);
  assert.match(app, /-webkit-text-stroke:\$\{textOutlineWidth\}px \$\{textOutline\}/);
  assert.match(app, /const preserveState = renderedSidecarKey === renderKey && !sidecar\.hidden/);
  assert.match(app, /details\.open = openDetails\[index\] \?\? details\.open/);
  assert.match(app, /sidecarContent\.scrollTop = scrollTop/);
  assert.match(app, /<strong>Node<\/strong>/);
  assert.match(app, /<strong>Flow<\/strong>/);
  assert.doesNotMatch(app, /data-line-field="id"/);
  assert.match(app, /flow: new Set\(\["\.from"[\s\S]*"\.annotation"/);
  assert.doesNotMatch(app, /flow: new Set\(\["\.id"/);
  assert.match(app, /--preview-graph-background:/);
  assert.match(app, /--preview-canvas-background:/);
  assert.match(app, /const graphBackground = includeGraph \? group\?\.fill \|\| "transparent" : "transparent"/);
  assert.match(app, /const canvasBackground = currentGraph\.figure\?\.background \|\| "#ffffff"/);
  assert.match(app, /previewStageBackground\(graphForNode\(node\.id\)\)/);
  assert.match(app, /previewStageBackground\(group\)/);
  assert.match(styles, /\.preview-stage \{[^}]*linear-gradient\(var\(--preview-graph-background, transparent\), var\(--preview-graph-background, transparent\)\), var\(--preview-canvas-background, #fff\)/);
  assert.match(styles, /\.canvas-inspector \.preview-annotation \{[^}]*margin: 0;[^}]*border-color: transparent;[^}]*background: transparent;/);
  assert.match(styles, /\.canvas-inspector \.preview-annotation:hover, \.canvas-inspector \.preview-annotation:focus-visible \{[^}]*border-color:[^}]*background:/);
  assert.match(styles, /\.canvas-inspector \.preview-annotation\.active-part \{[^}]*border-color:[^}]*background:/);
  assert.match(styles, /\.canvas-inspector details \{ margin: 8px 0 0; padding: 0;/);
  assert.match(styles, /\.canvas-inspector details\[open\] > :last-child:not\(summary\) \{ margin-bottom: 0; \}/);
  assert.match(styles, /\.inspector-sidecar details \{ margin: 8px 0 0; padding: 0;/);
  assert.match(styles, /\.inspector-sidecar details\[open\] > :last-child:not\(summary\) \{ margin-bottom: 0; \}/);
  assert.doesNotMatch(app, /<p class="preview-hint">/);
  assert.match(styles, /\.flow-preview-wrap \{[^}]*place-items: center;/);
  assert.match(app, /<summary>Connected flows <small>\$\{edges\.length\}<\/small><\/summary>/);
  assert.match(app, /openSidecar\("node-flow", \{ edgeKey: flowEntry\.dataset\.flowEntry \}\)/);
  assert.doesNotMatch(app, /<summary>Connections <small>/);
  assert.doesNotMatch(app, /class="connection-actions"/);
  assert.doesNotMatch(app, /Connect a new node here/);
  assert.match(app, /graphSelections\.length > 1[\s\S]*Align \/ distribute[\s\S]*return;/);
  assert.match(renderer, /event\.shiftKey \|\| event\.ctrlKey \|\| event\.metaKey/);
  assert.match(renderer, /event\.metaKey \|\| event\.ctrlKey \|\| event\.shiftKey/);
  assert.match(html, /id="color-picker-popup"[^>]*hidden/);
  assert.match(html, /id="color-picker-saturation"[^>]*canvas|<canvas id="color-picker-saturation"/);
  assert.match(html, /id="color-picker-hue" type="range"/);
  assert.match(html, /id="color-picker-alpha" type="range"/);
  assert.match(html, /id="color-picker-h" type="number"/);
  assert.match(html, /id="color-picker-s" type="number"/);
  assert.match(html, /id="color-picker-v" type="number"/);
  assert.match(html, /id="color-picker-marker"/);
  assert.doesNotMatch(html, /id="color-picker-popup-none"/);
  assert.doesNotMatch(html, /color-picker-popup-input[^>]*type="color"/);
  assert.match(app, /popupAlpha/);
  assert.match(app, /Math\.round\(popupAlpha \* 255\)/);
  assert.match(app, /function openColorPickerPopup\(trigger, value, apply\)/);
  assert.match(app, /"sbd-color"/);
  assert.match(app, /match\[6\] \? "sbd-color"/);
  assert.match(app, /@\(\?:node\|flow\|line\|annotation\)\\b/);
  assert.match(app, /const cssPropertyLabels = \{/);
  assert.match(app, /node: \["shape", "fill", "color"/);
  assert.match(app, /flow: \["color", "outline", "outline-width", "width", "arrow-style"/);
  assert.match(app, /annotation: \["color", "font-family"/);
  assert.match(app, /activeDocument === "css"\) return cssCompletionContext\(caret\)/);
  assert.match(app, /if \(!match \|\| declaration !== match\[1\]\) return \{ items: \[\]/);
  assert.match(app, /if \(\/\^\[a-z@\.\#-\]\$\/i\.test\(event\.data \?\? ""\)\) showCompletions\(\)/);
  assert.doesNotMatch(app, /event\.inputType === "insertLineBreak"[^;]*showCompletions/);
  assert.match(app, /if \(\/\^@graph\\b\/\.test\(parent\)\) return "graphStyle"/);
  assert.match(styles, /::highlight\(sbd-color\)/);
  assert.match(styles, /::highlight\(sbd-number\)/);
  assert.match(diagramStyles, /--diagram-annotation: #000000/);
  const darkTheme = styles.match(/:root\[data-theme="dark"\]\s*\{([^}]*)\}/)?.[1];
  assert.ok(darkTheme, "could not locate the dark application theme");
  assert.doesNotMatch(darkTheme, /--diagram-/);
  assert.match(renderer, /annotation: read\("--diagram-annotation", "#000000"\)/);
  assert.doesNotMatch(html, /builder-diagram-no-(?:fill|outline)/);
  assert.match(app, />Send to front<\/option><option value="back">Send to back/);
  assert.doesNotMatch(app, /New front layer/);
  assert.match(app, /data-connected-field="source-face"/);
  assert.match(app, /data-connected-field="target-face"/);
  assert.match(app, /<summary>Connected flows <small>/);
  assert.doesNotMatch(app, /data-connected-field="arrow-style"/);
  assert.doesNotMatch(app, /data-connected-field="width"/);
  assert.doesNotMatch(app, /data-connected-field="roundness"/);
  assert.match(app, /data-line-field="arrow-style"/);
  assert.match(app, /data-line-field="stroke-style"/);
  assert.match(app, /data-line-field="roundness"/);
  assert.match(app, /data-line-field="outline-width"/);
  assert.match(app, /\["triangle", "open", "diamond", "circle", "chunky"\]/);
  assert.match(app, /Arrow height<input data-line-field="arrow-height"/);
  assert.match(app, /Arrow head width<input data-line-field="arrow-head-width"/);
  assert.doesNotMatch(app, /Chunky arrows pair the flow colour/);
  assert.match(renderer, /function chunkyArrowPath\(routeD, direction, arrowHeight, arrowHeadWidth\)/);
  assert.match(renderer, /class: `connector chunky \$\{edge\.kind\}`[\s\S]*fill: color[\s\S]*stroke: hasOutline \? outline : "none"/);
  assert.match(app, /function previewChunkyArrowMarkup\(start, end, direction, color, outline, outlineWidth, arrowHeight, arrowHeadWidth\)/);
    assert.doesNotMatch(app, /ID <small>optional<\/small><input data-line-field="id"/);
  assert.match(app, /colorControl\("Outline", "outline"/);
  assert.match(app, /endpointInput\("from", edge\.from, edge\.to\)/);
  assert.match(app, /endpointInput\("to", edge\.to, edge\.from\)/);
  assert.match(app, /<input data-line-endpoint="\$\{field\}"[^>]*list="\$\{listId\}"/);
  assert.match(app, /<datalist id="\$\{listId\}">/);
  assert.match(app, /flowEndpointNodes\(edge\)\.some\(\(node\) => node\.id === endpoint\)/);
  assert.match(app, /data-line-face="source-face"/);
  assert.match(app, /data-line-face="target-face"/);
  assert.match(app, /Auto \(\$\{effective\}\)/);
  assert.match(app, /selectionKey: `line:\$\{from\}:\$\{to\}:\$\{edge\.lineNumber\}`/);
  assert.match(app, /function deleteCanvasSelection\(\) \{\s*closeSidecar\(\);/);
  assert.match(html, /class="inspector-footer"[^>]*>.*id="save-reusable-style"/);
  assert.match(styles, /\.canvas-inspector \.inspector-preset-bar \{[^}]*color: var\(--accent\);[^}]*border-color: color-mix\(in srgb, var\(--accent\) 55%, var\(--border\)\);[^}]*background: color-mix\(in srgb, var\(--accent\) 9%, var\(--surface\)\);/);
  assert.match(html, /id="style-builder-preview"[^>]*readonly/);
  assert.match(html, /<button class="primary" value="default">Save<\/button>/);
  assert.doesNotMatch(app, />Save as reusable (?:node|line|annotation) type/);
  assert.match(app, /<label class="inspector-id-field">ID \(optional\)<input data-node-field="id"/);
  assert.match(app, /data-add-annotation>\+ Add Annotation/);
  assert.match(app, /data-add-line-annotation>\+ Add Annotation/);
  assert.match(app, /openAnnotationBuilder\("line"\)/);
  assert.match(html, /id="annotation-builder-position-row"/);
  assert.match(app, /annotationChip\("flow-annotations", "above", annotations, "annotation"\)/);
  assert.doesNotMatch(app, /annotationChip\("flow-annotations", "below"/);
  assert.match(app, /appendFlowAnnotation\(source\.value, edge\.lineNumber/);
  assert.match(app, /document\.querySelector\("#annotation-builder-position-row"\)\.hidden = target === "line"/);
  assert.match(html, /id="annotation-builder-text"/);
  assert.match(html, /id="annotation-builder-text-outline"/);
  assert.match(html, /id="annotation-builder-text-outline-width"/);
  assert.doesNotMatch(html, /node-annotation-only/);
  assert.match(app, /data-flow-annotation-field/);
  assert.match(app, /setAnnotationText\(source\.value, flowAnnotationLine/);
  assert.match(app, /if \(annotation\.legacy\) return legacyFlowAnnotationEditor\(edge, annotation\.position\)/);
  assert.match(app, /CSS\.supports\("color"/);
  assert.match(app, /currentTrigger\?\.style\.setProperty\("--swatch", color\)/);
  assert.doesNotMatch(styles, /\.color-decorator \{/);
  assert.doesNotMatch(html, /color-decorators/);
  assert.doesNotMatch(app, /renderColorDecorators|colorDecorators/);
  assert.doesNotMatch(app, /Number\(swatch\.dataset\.line\) \* 20 - source\.scrollTop/);
  assert.doesNotMatch(app, /Number\(swatch\.dataset\.length\)\) \* 7\.23 - source\.scrollLeft/);
  assert.doesNotMatch(styles, /^\.color-popup-trigger \{[^}]*position: relative/m);
  assert.match(styles, /\.inspector-color \.color-popup-trigger \{ position: relative; \}/);
  assert.match(styles, /\.color-popup-trigger::after[^}]*background: var\(--swatch, #000\)/);
  assert.match(styles, /\.color-picker-heading > span::after[^}]*background: var\(--preview-color, transparent\)/);
  assert.match(app, /\^#\[0-9a-f\]\{6\}00\$\/i\.test\(color\)/);
  assert.match(renderer, /const annotations = edge\.annotations \?\? \[\]/);
  assert.match(renderer, /function textBorder/);
  assert.match(renderer, /!visualNodes\.length && !groups\.length.*empty-diagram/);
  assert.match(diagramStyles, /\.pugflow-svg\.empty-diagram \{\s*display: none;/);
  assert.match(renderer, /class: `connector connector-outline/);
  assert.match(renderer, /class: "block-annotation"[\s\S]*?"data-select-kind": "node", "data-selection-key": `node:\$\{node\.id\}`/);
  assert.doesNotMatch(renderer, /"data-select-kind": "annotation"/);
  assert.match(renderer, /kind === "line" \? selectedTarget\.dataset\.offsetLine/);
  assert.match(app, /data-delete-annotation/);
  assert.match(app, /data-remove-annotation-offset/);
  assert.doesNotMatch(app, /data-group-as-graph|Group as Graph|\.members/);
  assert.match(html, /id="builder-from-graph"/);
  assert.match(html, /id="builder-to-graph"/);
  assert.match(html, /id="builder-sources"[^>]*role="listbox"/);
  assert.match(html, /id="builder-targets"[^>]*role="listbox"/);
  assert.match(html, /id="builder-from-direction"/);
  assert.match(html, /id="builder-to-direction"/);
  assert.match(html, /id="builder-connected-node" readonly/);
  assert.match(html, /class="connected-node-only connected-node-summary"[\s\S]*id="builder-connected-node" readonly[\s\S]*>Face<input id="builder-connected-face" readonly/);
  assert.match(html, /class="flow-only existing-flow-only">From direction/);
  assert.match(styles, /\.connected-node-summary \{[^}]*width: 100%;[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/);
  assert.match(styles, /#graph-builder\[data-mode="connected-node"\] \.existing-flow-only/);
  assert.match(styles, /#graph-builder\[data-mode="connected-node"\] \.flow-endpoints \{ grid-template-columns: minmax\(0, 1fr\); \}/);
  assert.match(html, /id="builder-flow-direction"/);
  assert.match(html, /id="builder-new-node-graph"/);
  assert.match(app, /data-node-graph/);
  assert.match(app, /<label>Layer \(\$\{node\.layer \?\? 0\}\)<select data-node-layer-order>/);
  assert.match(app, /moveNodeToGraph\(nextSource, movingNode\.lineNumber, parsedTarget\.lineNumber\)/);
  assert.match(html, /id="toggle-layers"/);
  assert.match(html, /id="layers-list"[^>]*role="list"/);
  assert.match(html, /id="graph-browser-select"/);
  assert.match(html, /id="graph-nodes-list"[^>]*role="list"/);
  assert.match(html, /id="graph-flows-list"[^>]*role="list"/);
  assert.match(html, /id="graph-panel-resizer"[^>]*role="separator"/);
  assert.match(html, /class="toggle-label">Objects/);
  assert.match(html, /class="layers-title">[\s\S]*?<h2>Objects<\/h2>/);
  assert.match(html, /class="graph-browser-section graph-ordering" open>\s*<summary>Graphs <small id="graph-count">0<\/small><\/summary>/);
  assert.doesNotMatch(html, /Drag graphs to reorder them\. The top graph renders in front\./);
  assert.match(app, /data-browser-node/);
  assert.match(app, /draggable="true" data-browser-node/);
  assert.match(app, /data-node-layer-order/);
  assert.match(app, /applyNodeLayerOrders/);
  assert.match(app, /data-browser-flow/);
  assert.match(app, /setGraphPanelWidth/);
  assert.match(app, /setProperty\("--layers-open-width"/);
  assert.match(app, /pugflow-layers-width-v1/);
  assert.match(styles, /\.layers-panel \{[^}]*overflow-y: auto/);
  assert.match(styles, /\.graph-panel-resizer/);
  assert.match(styles, /main\.layers-collapsed \.layers-toggle \{[^}]*opacity: 1;[^}]*background-color: var\(--panel\)/);
  assert.match(styles, /--layers-width: var\(--layers-open-width\)/);
  assert.match(styles, /main\.layers-collapsed \{ --layers-width: 0px;/);
  assert.match(styles, /\.graph-browser \{[^}]*border-top:/);
  assert.match(styles, /\.node-layer-item/);
  assert.match(styles, /\.node-layer-copy/);
  assert.match(styles, /\.object-hidden[^}]*text-decoration: line-through/);
  assert.doesNotMatch(styles, /\.object-hidden[^}]*font-style:\s*italic/);
  assert.match(html, /<main class="layers-collapsed">/);
  assert.match(html, /class="toggle-label">Source/);
  assert.doesNotMatch(html, /class="toggle-label">Graphs/);
  assert.match(app, /draggable="true" data-layer-graph/);
  assert.match(app, /layer-item\$\{group\.hidden \? " object-hidden" : ""\}/);
  assert.match(app, /node-layer-item\$\{node\.hidden \? " object-hidden" : ""\}/);
  assert.match(app, /graph-item\$\{edge\.hidden \? " object-hidden" : ""\}/);
  assert.match(app, /graphs selected<\/h3>[\s\S]*data-graph-hidden/);
  assert.match(app, /setStructuralField\(nextSource, group\.lineNumber, "layer"/);
  assert.match(app, /const targetGraph = sourceGraph/);
  assert.doesNotMatch(app, /removeNodeFields\(nextSource, node\.lineNumber, \["offset", "label-offset"\]\)/);
  assert.doesNotMatch(app, /change\.kind === "route"/);
  assert.match(app, /cleanupAlignmentOffsets[\s\S]*cleanupGraphOffsets[\s\S]*setNodeOffsetField[\s\S]*setDeclarationOffsetField/);
  assert.match(renderer, /"data-drag-kind": "graph-label"/);
  assert.match(renderer, /Math\.max\(sourceLayer, targetLayer\)/);
  assert.match(renderer, /class: "diagram-layer"/);
  assert.match(renderer, /class: "connector-hit"/);
  assert.match(renderer, /"stroke-width": Math\.max\(14, edge\.width \+ 10\)/);
  assert.match(renderer, /"data-select-kind": "line"/);
  assert.match(renderer, /function exportSvgClone\(svg, layout, graphId = ""\)/);
  assert.match(renderer, /function toSVGString\(graphId = ""\)/);
  assert.match(renderer, /function toPNGBlob\(scale = 2, graphId = ""\)/);
  assert.match(renderer, /nodeIds\.has\(element\.dataset\.from\).*nodeIds\.has\(element\.dataset\.to\)/);
  assert.match(renderer, /\(a\.layer \?\? 0\) - \(b\.layer \?\? 0\)/);
  assert.ok(renderer.indexOf('class: "connector-layer"') < renderer.indexOf('class: "graph-node-layer"'));
  assert.doesNotMatch(html, /id="add-merge"/);
  assert.match(styles, /\.inspector-drag-handle \{ position: sticky/);
  assert.match(styles, /\.canvas-inspector \{ position: fixed/);
  assert.match(app, /canvasShell\.getBoundingClientRect\(\)/);
  assert.match(app, /new ResizeObserver\(constrainInspectorToCanvas\)\.observe\(canvasShell\)/);
  assert.match(app, /canvasShell\.addEventListener\("wheel", \(event\) => \{\s+if \(inspector\.contains\(event\.target\) \|\| sidecar\.contains\(event\.target\)\) return;/);
  assert.match(styles, /writing-mode: vertical-rl/);
  assert.match(styles, /\.inspector-footer \{ position: sticky/);
  assert.match(styles, /button\.danger[^}]*var\(--danger\)[^}]*background:/);
  assert.match(styles, /\.subdiagram-selection-outline \{ opacity: 0/);
  assert.match(styles, /svg\.interactive \.subdiagram-hit:hover ~ \.subdiagram-selection-outline/);
  assert.match(styles, /opacity: var\(--graph-proximity/);
  assert.ok(renderer.indexOf('class: "subdiagram-frame"') < renderer.indexOf('class: "subdiagram-selection-outline"'));
  assert.match(styles, /selected-element > \.subdiagram-selection-outline \{ opacity: 1/);
  assert.doesNotMatch(styles, /:focus > \.subdiagram-selection-outline/);
  assert.doesNotMatch(app, /<summary>Typography<\/summary>/);
});

test("application startup does not wait for the math renderer", () => {
  const html = readFileSync(new URL("../../src/pugflow/web/index.html", import.meta.url), "utf8");
  const appImport = html.indexOf('import("./app.mjs")');
  const mathAwait = html.indexOf("await window.MathJax.startup.promise");
  assert.ok(appImport >= 0 && mathAwait >= 0 && appImport < mathAwait);
  assert.match(html, /pugflow-math-ready/);
});

test("Pages deployments cache-bust browser assets", () => {
  const workflow = readFileSync(new URL("../../.github/workflows/test-and-publish.yml", import.meta.url), "utf8");
  assert.match(workflow, /name: Cache-bust browser assets/);
  assert.match(workflow, /ASSET_VERSION: \$\{\{ github\.sha \}\}/);
  assert.match(workflow, /(?:css\|mjs)/);
});
